name: Deploy NestJS Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Set EC2 IP with fallback to default
    - name: Set EC2 IP
      id: set-ec2-ip
      run: |
        if [ -z "${{ secrets.DYNAMIC_EC2_IP }}" ]; then
          echo "Using default EC2 IP"
          echo "EC2_IP=<DEFAULT_EC2_IP>" >> $GITHUB_ENV
        else
          echo "Using dynamic EC2 IP from secrets"
          echo "EC2_IP=${{ secrets.DYNAMIC_EC2_IP }}" >> $GITHUB_ENV
      env:
        DEFAULT_EC2_IP: "203.0.113.42" # REPLACE with your default EC2 IP

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
          cd ${{ secrets.PROJECT_FOLDER }}
          git pull origin main
          npm install
          npm run build
          pm2 restart all || pm2 start dist/src/main.js --name APIDESAFIO
        EOF