name: Deploy NestJS Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Set EC2 IP
    - name: Set EC2 IP
      run: echo "EC2_IP=${{ secrets.DYNAMIC_EC2_IP }}" >> $GITHUB_ENV

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP <<EOF
          cd $PROJECT_FOLDER
          git pull origin main
          npm install
          npx prisma migrate deploy
          npx prisma db seed
          npm run build
          pm2 restart all || pm2 start dist/src/main.js --name APIDESAFIO
        EOF